# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ci-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ci-${{ env.cache-name }}-
            ci-
      - name: Install node modules
        run: npm install
      
      - name: Install Jasmine
        run: npm install --save-dev jasmine jasmine-browser-runner jasmine-core
    
      - name: Init jasmine
        run: npx jasmine init
        
      - name: Init jasmine-browser-runner
        run: npx jasmine-browser-runner init

      - name: Run tests
        run: ng test --browsers ChromeHeadless
