# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ci-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ci-${{ env.cache-name }}-
            ci-
      - name: Start MongoDB v${{ matrix.node-version }}
        uses: superchargejs/mongodb-github-action@1.0.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: npm install and start server
        run: |
          npm ci
          npm start & npx wait-on http://localhost:5000
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}

      - name: npm install and start client
        run: |
          cd client
          npm ci
          npm start & npx wait-on http://localhost:3000

      - name: run test
        run: npm test
